### ISSUE TITLE
Numbers in template_data get replaced by strings

### ISSUE THREAD

**Issue by freeDom-** [daredoes/linked-lovelace-ui#17]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.3.5

**Last working release (if known):**

**Browser and Operating System:**
Android (EMUI 12.0.0) - not tested on other device

**Description of problem:**

I created a template using three placeholders. When using the card all three options show. After filling in values I get an erroroneous card, because the given number is converted to a string (inserted inside single quotes). This is not happening for the other two values.

**Javascript errors shown in the web inspector (if applicable):**

```
value.series[0].max is not a number
```

**Additional information:**

Compare template data with replacements.

```
template: radial-bar
template_data:
  entity: sensor.localhost_cpu_used
  color: green
  max: 100
type: custom:stack-in-card
cards:
  - type: custom:apexcharts-card
    chart_type: radialBar
    series:
      - entity: sensor.localhost_cpu_used
        color: green
        max: '100'
        show:
          legend_value: false
    apex_config:
      plotOptions:
        radialBar:
          offsetY: 0
          startAngle: -108
          endAngle: 108
          hollow:
            size: 70%
          dataLabels:
            name:
              show: false
            value:
              show: false
          track:
            strokeWidth: 80%
            margin: 0
      legend:
        show: false
      chart:
        height: 240
    card_mod:
      style: |
        ha-card {
          border: none;
        }
  - type: custom:mushroom-entity-card
    entity: sensor.localhost_cpu_used
    primary_info: name
    secondary_info: state
    name: CPU usage
    icon_color: green
    layout: vertical
    card_mod:
      style: |
        ha-card {
          margin-top: -90px;
          width: 140px;
          margin-left: auto;
          margin-right: auto;
          border: none;
        }
```

**Comment by daredoes** [comment]
I'll take a look at this soon!

**Comment by daredoes** [comment]
Okay so I have a new version I'm releasing, `v1.4.0`.

This will allow default values by changing two things. 

First, `template_data` is now called `ll_data`. Until v2, I will automatically transition users from `template_data` to `ll_data`, so they are interchangeable. This is to make sure I don't overshadow a key some other card may want to use.

Second, a new key of `ll_keys` can be added. It's type is an array of strings. Each string will be matched against a key in the `ll_data` object, and if a match is found, the value of that key in `ll_data` will be put/swapped into the template card with the given key. 

If a key is given, and the `ll_data` has a number type value matched to that key, then the template will now have a number type value

YAML Examples

Template card with default value
```yaml
type: markdown
count: 6
```

Card using template and overwriting default value
```yaml
template: 'template'
ll_data:
    count: 4
ll_keys:
    - count
```

Should result in the final card

```yaml
type: markdown
template: 'template'
ll_data:
    count: 4
ll_keys:
    - count
count: 4
```
