### ISSUE TITLE
Syntaxerror Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by mobiledude** [daredoes/linked-lovelace-ui#19]
Getting the following error in HA. I am running latest HA Beta. Is there a way to resolve this?

Logger: frontend.js.latest.202302020
Source: components/system_log/__init__.py:254
/hacsfiles/linked-lovelace-ui/linked-lovelace-ui.js?hacstag=559360809135:84:0 SyntaxError: Invalid regular expression: invalid group specifier name

**Comment by daredoes** [comment]
don't run the beta, it's out of date

**Comment by mobiledude** [comment]
Home Assistant 2023.3.0b5
Frontend-versie: 20230224.0 - latest
 and your integration 1.3.5
What is out of date? I do not understand?

**Comment by daredoes** [comment]
I thought you meant the beta version of the repo. my bad

**Comment by daredoes** [comment]
Could you provide the YAML of the template card, and the YAML of the card that consumes the template?

**Comment by mobiledude** [comment]
I have no cards yet, since I could not get it working. This error pops-up in HA logs even without cards and just the installation  of your hacs inegration

**Comment by daredoes** [comment]
I am removing the RegEx handling in Linked Lovelace, and so this issue should become a non-issue
