### ISSUE TITLE
Error in System Logs when restarting HA in v1.4.5

### ISSUE THREAD

**Issue by StephaneStolz** [daredoes/linked-lovelace-ui#23]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:** v1.4.5

**Last working release (if known):** I wasn't checking the logs so often with the previous version, so I don't know

**Browser and Operating System:**
```
Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230302.0 - latest
```

**Description of problem:**

Whenever I restart Home Assistant, I have the following error in the System Logs

**Javascript errors shown in the web inspector (if applicable):**

```
Logger: frontend.js.latest.202303020
Source: components/system_log/__init__.py:254
First occurred: 11:50:33 (1 occurrences)
Last logged: 11:50:33

http://192.168.0.11:8123/hacsfiles/linked-lovelace-ui/linked-lovelace-ui.js?hacstag=559360809145:84:0 SyntaxError: Invalid regular expression: invalid group specifier name
```

**Additional information:**

**Comment by daredoes** [comment]
duplicate of #19 
Doesn't seem to break anything AFAIK, but definitely not great

**Comment by StephaneStolz** [comment]
Agreed that it doesn't break anything
As it is a duplicate, I will close this issue so it doesn't clog your issues list.

Thanks for the prompt response
