### ISSUE TITLE
Rewriting custom:button-card state values

### ISSUE THREAD

**Issue by jeffchampagne** [daredoes/linked-lovelace-ui#25]
I'm running into an issue where my button-card state values are being re-written upon updating the templates which is then causing a type error.

Original YAML:

`type: custom:button-card`
`entity: input_select.home_mode`
`name: Home`
`icon: mdi:home`
`aspect_ratio: 5/1`
`state:`
`  - value: Home`
`    styles:`
`      card:`
`        - background-color: '#457b9d'`
`tap_action:`
`  action: call-service`
`  service: input_select.select_option`
`  service_data:`
`    entity_id: input_select.home_mode`
`    option: Home`

Gets re-written to:
`type: custom:button-card`
`    entity: input_select.home_mode`
`    name: Home`
`    icon: mdi:home`
`    aspect_ratio: 5/1`
`    state:`
`      - value: Home`
`        styles:`
`          card:`
`            '0':`
`              background-color: '#457b9d'`
`    tap_action:`
`      action: call-service`
`      service: input_select.select_option`
`      service_data:`
`        entity_id: input_select.home_mode`
`        option: Home`

This piece specifically is throwing the error:
`card:`
`     '0':`
`        background-color: '#457b9d'`

**Comment by daredoes** [comment]
Weird. Looks like its interpreting the contents as an array instead of an object, or maybe that's just how I'm placing it back in?

I'll try to look at this soon™

I haven't given Linked Lovelace UI some love in a hot minute

**Comment by jeffchampagne** [comment]
Thanks a lot! I really love linked-lovelace. Saves me SO much time re-copying YAML between dashboards.

**Comment by damru** [comment]
I'm having the same issue. Had to go back to decluttering-card in the meantime.
Thanks for the good work though! I'm eagerly waiting for this fix 👀

**Comment by giu889** [comment]
I think I have found what causes the bug. `DashboardCard` has a field called `card` that is used by this code in `helper.ts` to store data. This clashes with Lovelace configuration entries that have a key with the same name:

```javascript
if (data.cards) {
  const cards: DashboardCard[] = [];
  data.cards.forEach((card) => {
    if (dataFromTemplate) {
      card.ll_data = { ...(card.ll_data || {}), ...dataFromTemplate };
    }
    cards.push(Object.assign({}, updateCardTemplate(card, templateData)));
  });
  data.cards = cards;
}
if (data.card) {
  if (dataFromTemplate) {
    data.card.ll_data = { ...(data.card.ll_data || {}), ...dataFromTemplate };
  }
  data.card = Object.assign({}, updateCardTemplate(data.card, templateData));
}
```
```javascript
if (cardKey !== 'card' && typeof data[cardKey] === 'object') { ...
```

I was able to "fix" it for myself by manually changing the field's name in the `linked-lovelace-ui.js` file.
