### ISSUE TITLE
works only for additional dashboards but not the original one (/lovelace)

### ISSUE THREAD

**Issue by stefanschaedeli** [daredoes/linked-lovelace-ui#4]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.2.5

**Last working release (if known):**

**Browser and Operating System:**
mac os
firefox

windows 10 - edge

**Description of problem:**
my default dashboard (overview) is not listed in the dashboards of the plugin. all other dashboards work great.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by stefanschaedeli** [comment]
<img width="1676" alt="Bildschirmfoto 2022-11-29 um 15 29 50" src="https://user-images.githubusercontent.com/53369648/204556412-6e6e7947-d625-4d19-b63e-5d96277c2293.png">
<img width="325" alt="Bildschirmfoto 2022-11-29 um 15 29 40" src="https://user-images.githubusercontent.com/53369648/204556419-44b646cc-9a5f-4265-a012-72e0406a47f8.png">

**Comment by daredoes** [comment]
Hey @stefanschaedeli ! Thanks for using the plugin!

I've noticed this issue as well. Unfortunately, the "Overview" dashboard is treated different than the user-created dashboards by Home Assistant, so I can't touch it (for now). 

I do have a solution though, [Default Dashboard](https://github.com/daredoes/default-dashboard), a plugin I've also made that let's you change the default dashboard for all devices automatically. I use this to navigate all my users to a dashboard called "Home" instead of "Overview".

I've put in a PR to have it added to the HACs default repository. Hopefully it'll be there soon, and I hope this helps!

**Comment by stefanschaedeli** [comment]
Thank you @daredoes  for the fast response. I though about this as the cause but before I move all my existing work into a new dashboard having to fix all the links I very happy to have certnatly that there is not other option :)

Anyhow, your work is amazing and im so happy I found this. I did also make a WTH entry about this gap of not having template cards :)

Thanks also for the default dashboard fix.

**Comment by stefanschaedeli** [comment]
ah yeah, on another note, maybe mention this in the guide as a limitation :)

**Comment by daredoes** [comment]
@stefanschaedeli I'll be updating the guide soon. I added a new card that let's you quickly know what templates are available, and have support for `template_data` by surrounding anything in a template card with `$`

Let's say my template card is called `template` and is defined as:
```yaml
type: 'markdown-card'
name: '$name$'
```

Then my card that uses it would be:
```yaml
type: 'whocares'
template: 'template'
template_data:
    name: 'My Custom Name'
```

which once updated by Linked Lovelace will produce the following card
```yaml
type: 'markdown-card'
name: 'My Custom Name'
template: 'template'
template_data:
    name: 'My Custom Name'
```

**Comment by daredoes** [comment]
For reference, I use this to make a template card that has other template cards in it.

The following card takes the template data
```yaml
template_data:
    mode_a: ''
    mode_b: ''
    mode_c: ''
    entity_id: ''
```
and puts the `mode_a` in the `template_data` section of the first card, `mode_b` in the second, etc.

The `entity_id` is passed down to children templates so that when they are rendered, they use the value from the top-most template.

The card itself let's me select a value from an `input_select` helper, while also having predefined icons/colors for all the different values I expect from my input_selects. For my purposes, the input_selects have their values retrieved from another source automatically, namely WLED presets.

```yaml
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - template: mode-button
        template_data:
          mode: $mode_a$
          entity_id: ''
        type: vertical-stack
        cards:
          - type: custom:mushroom-template-card
            primary: ''
            secondary: $mode_a$
            icon: |-
              {% set mode = '$mode_a$'|lower %}
              {% if mode == 'passive' %}
              mdi:peace
              {% elif mode == 'gaming' %}
              mdi:controller
              {% elif mode == 'chill' %}
              mdi:sunglasses
              {% elif mode == 'off' %}
              mdi:power
              {% elif mode == 'romance' %}
              mdi:heart
              {% elif mode == 'party' %}
              mdi:party-popper
              {% elif mode == 'meeting' %}
              mdi:briefcase-account
              {% elif mode == 'movie' %}
              mdi:video
              {% elif mode == 'sleeping' %}
              mdi:sleep
              {% elif mode == 'nightlight' %}
              mdi:ninja
              {% else %}
              mdi:progress-question
              {% endif %}
            entity: $entity_id$
            badge_icon: |-
              {% set myMode = '$mode_a$' %}
              {% if is_state(entity, myMode) %}
              mdi:check-circle-outline
              {% endif %}
            badge_color: green
            layout: vertical
            tap_action:
              action: call-service
              service: input_select.select_option
              data:
                option: $mode_a$
              target:
                entity_id: $entity_id$
            icon_color: |-
              {% set mode = '$mode_a$'|lower %}
              {% if mode == 'passive' %}

              {% elif mode == 'gaming' %}
              purple
              {% elif mode == 'chill' %}
              blue
              {% elif mode == 'off' %}
              red
              {% elif mode == 'romance' %}
              pink
              {% elif mode == 'party' %}
              yellow
              {% elif mode == 'meeting' %}
              red
              {% elif mode == 'movie' %}
              orange
              {% elif mode == 'sleeping' %}

              {% elif mode == 'nightlight' %}

              {% else %}

              {% endif %}
            fill_container: true
            multiline_secondary: true
      - template: mode-button
        template_data:
          mode: $mode_b$
          entity_id: ''
        type: vertical-stack
        cards:
          - type: custom:mushroom-template-card
            primary: ''
            secondary: $mode_b$
            icon: |-
              {% set mode = '$mode_b$'|lower %}
              {% if mode == 'passive' %}
              mdi:peace
              {% elif mode == 'gaming' %}
              mdi:controller
              {% elif mode == 'chill' %}
              mdi:sunglasses
              {% elif mode == 'off' %}
              mdi:power
              {% elif mode == 'romance' %}
              mdi:heart
              {% elif mode == 'party' %}
              mdi:party-popper
              {% elif mode == 'meeting' %}
              mdi:briefcase-account
              {% elif mode == 'movie' %}
              mdi:video
              {% elif mode == 'sleeping' %}
              mdi:sleep
              {% elif mode == 'nightlight' %}
              mdi:ninja
              {% else %}
              mdi:progress-question
              {% endif %}
            entity: $entity_id$
            badge_icon: |-
              {% set myMode = '$mode_b$' %}
              {% if is_state(entity, myMode) %}
              mdi:check-circle-outline
              {% endif %}
            badge_color: green
            layout: vertical
            tap_action:
              action: call-service
              service: input_select.select_option
              data:
                option: $mode_b$
              target:
                entity_id: $entity_id$
            icon_color: |-
              {% set mode = '$mode_b$'|lower %}
              {% if mode == 'passive' %}

              {% elif mode == 'gaming' %}
              purple
              {% elif mode == 'chill' %}
              blue
              {% elif mode == 'off' %}
              red
              {% elif mode == 'romance' %}
              pink
              {% elif mode == 'party' %}
              yellow
              {% elif mode == 'meeting' %}
              red
              {% elif mode == 'movie' %}
              orange
              {% elif mode == 'sleeping' %}

              {% elif mode == 'nightlight' %}

              {% else %}

              {% endif %}
            fill_container: true
            multiline_secondary: true
      - template: mode-button
        template_data:
          mode: $mode_c$
          entity_id: ''
        type: vertical-stack
        cards:
          - type: custom:mushroom-template-card
            primary: ''
            secondary: $mode_c$
            icon: |-
              {% set mode = '$mode_c$'|lower %}
              {% if mode == 'passive' %}
              mdi:peace
              {% elif mode == 'gaming' %}
              mdi:controller
              {% elif mode == 'chill' %}
              mdi:sunglasses
              {% elif mode == 'off' %}
              mdi:power
              {% elif mode == 'romance' %}
              mdi:heart
              {% elif mode == 'party' %}
              mdi:party-popper
              {% elif mode == 'meeting' %}
              mdi:briefcase-account
              {% elif mode == 'movie' %}
              mdi:video
              {% elif mode == 'sleeping' %}
              mdi:sleep
              {% elif mode == 'nightlight' %}
              mdi:ninja
              {% else %}
              mdi:progress-question
              {% endif %}
            entity: $entity_id$
            badge_icon: |-
              {% set myMode = '$mode_c$' %}
              {% if is_state(entity, myMode) %}
              mdi:check-circle-outline
              {% endif %}
            badge_color: green
            layout: vertical
            tap_action:
              action: call-service
              service: input_select.select_option
              data:
                option: $mode_c$
              target:
                entity_id: $entity_id$
            icon_color: |-
              {% set mode = '$mode_c$'|lower %}
              {% if mode == 'passive' %}

              {% elif mode == 'gaming' %}
              purple
              {% elif mode == 'chill' %}
              blue
              {% elif mode == 'off' %}
              red
              {% elif mode == 'romance' %}
              pink
              {% elif mode == 'party' %}
              yellow
              {% elif mode == 'meeting' %}
              red
              {% elif mode == 'movie' %}
              orange
              {% elif mode == 'sleeping' %}

              {% elif mode == 'nightlight' %}

              {% else %}

              {% endif %}
            fill_container: true
            multiline_secondary: true
  - type: horizontal-stack
    cards:
      - template: mode-button
        template_data:
          mode: 'Off'
          entity_id: ''
        type: vertical-stack
        cards:
          - type: custom:mushroom-template-card
            primary: ''
            secondary: 'Off'
            icon: |-
              {% set mode = 'Off'|lower %}
              {% if mode == 'passive' %}
              mdi:peace
              {% elif mode == 'gaming' %}
              mdi:controller
              {% elif mode == 'chill' %}
              mdi:sunglasses
              {% elif mode == 'off' %}
              mdi:power
              {% elif mode == 'romance' %}
              mdi:heart
              {% elif mode == 'party' %}
              mdi:party-popper
              {% elif mode == 'meeting' %}
              mdi:briefcase-account
              {% elif mode == 'movie' %}
              mdi:video
              {% elif mode == 'sleeping' %}
              mdi:sleep
              {% elif mode == 'nightlight' %}
              mdi:ninja
              {% else %}
              mdi:progress-question
              {% endif %}
            entity: $entity_id$
            badge_icon: |-
              {% set myMode = 'Off' %}
              {% if is_state(entity, myMode) %}
              mdi:check-circle-outline
              {% endif %}
            badge_color: green
            layout: vertical
            tap_action:
              action: call-service
              service: input_select.select_option
              data:
                option: 'Off'
              target:
                entity_id: $entity_id$
            icon_color: |-
              {% set mode = 'Off'|lower %}
              {% if mode == 'passive' %}

              {% elif mode == 'gaming' %}
              purple
              {% elif mode == 'chill' %}
              blue
              {% elif mode == 'off' %}
              red
              {% elif mode == 'romance' %}
              pink
              {% elif mode == 'party' %}
              yellow
              {% elif mode == 'meeting' %}
              red
              {% elif mode == 'movie' %}
              orange
              {% elif mode == 'sleeping' %}

              {% elif mode == 'nightlight' %}

              {% else %}

              {% endif %}
            fill_container: true
            multiline_secondary: true

```

**Comment by stefanschaedeli** [comment]
Amazing:) great stuff :) hen 
I'm going a slightly different approach by comining your solution with entity filter card and other magic ;) 

Created now a navigation template, that cascades in a area template, that then is populated by your template data variable... super nice!  I can now choose or even dynamically load rooms, floors, house etc, always with the exact same ordering and style of a dashboard. Correction now apply all rooms instantly... I so happy 🗡️ 
<img width="1681" alt="Bildschirmfoto 2022-12-02 um 08 55 55" src="https://user-images.githubusercontent.com/53369648/205244035-89252bec-400d-4163-a288-c69f9899dc4c.png">
<img width="1686" alt="Bildschirmfoto 2022-12-02 um 08 55 47" src="https://user-images.githubusercontent.com/53369648/205244041-0dcf5e99-0c99-49ad-8196-59b49b6bfa3f.png">

`type: vertical-stack
cards:
  - template: nav2
    type: custom:layout-card
    cards:
      - type: custom:mushroom-entity-card
        entity: input_button.nav_home
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_car
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_bath
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_gaeste
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_kuche
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_sibylle
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_wohnzimmer
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_og_bad
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_og_nord
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_og_schlafzimmer
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_og_sud
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
      - type: custom:mushroom-entity-card
        entity: input_button.nav_og_wohnzimmer
        tap_action:
          action: navigate
          navigation_path: /lovelace
        secondary_info: none
        fill_container: false
        primary_info: name
        layout: horizontal
    layout:
      width: 70
      max_width: 800
      max_cols: 15
    layout_type: custom:horizontal-layout
  - type: custom:layout-card
    layout_type: custom:horizontal-layout
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: ''
            subtitle: Lichter
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              layout_type: custom:horizontal-layout
              layout:
                width: 100
                max_width: 800
                max_cols: 1
                title: test
            card_param: cards
            filter:
              include:
                - domain: light
                  area: $area$
                  options:
                    type: custom:mushroom-light-card
                    show_brightness_control: true
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
              exclude:
                - state: unavailable
            sort:
              method: none
              reverse: false
              numeric: false
            show_empty: false
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: ''
            subtitle: Schalter
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              layout_type: custom:horizontal-layout
              layout:
                width: 100
                max_width: 800
                max_cols: 3
            card_param: cards
            filter:
              include:
                - domain: switch
                  area: $area$
                  options:
                    type: custom:mushroom-entity-card
                    show_brightness_control: true
                    secondary_info: state
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                    layout: vertical
              exclude:
                - hidden_by: '*'
            sort:
              method: none
              reverse: false
              numeric: false
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: ''
            subtitle: Szenen
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              layout_type: custom:horizontal-layout
              layout:
                width: 200
                max_width: 800
                max_cols: 3
            card_param: cards
            filter:
              include:
                - domain: scene
                  area: $area$
                  options:
                    type: custom:mushroom-entity-card
                    show_brightness_control: true
                    secondary_info: false
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                    layout: vertical
              exclude:
                - hidden_by: '*'
            sort:
              method: none
              reverse: false
              numeric: false
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: ''
            subtitle: Buttons
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              layout_type: custom:horizontal-layout
              layout:
                width: 200
                max_width: 800
                max_cols: 3
            card_param: cards
            filter:
              include:
                - domain: input_button
                  area: $area$
                  options:
                    type: custom:mushroom-entity-card
                    show_brightness_control: true
                    secondary_info: false
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                    layout: vertical
              exclude:
                - hidden_by: '*'
            sort:
              method: none
              reverse: false
              numeric: false
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: ''
            subtitle: Mediaplayer
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              layout_type: custom:horizontal-layout
              layout:
                width: 200
                max_width: 800
                max_cols: 1
            card_param: cards
            filter:
              include:
                - domain: media_player
                  area: $area$
                  options:
                    type: custom:mini-media-player
                    layout: vertical
              exclude:
                - state: unavailable
            sort:
              method: none
              reverse: false
              numeric: false
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: ''
            subtitle: Storen
          - type: custom:auto-entities
            card:
              type: custom:layout-card
              layout_type: custom:horizontal-layout
              layout:
                width: 200
                max_width: 800
                max_cols: 1
            card_param: cards
            filter:
              include:
                - domain: cover
                  area: $area$
                  options:
                    type: custom:mushroom-cover-card
                    show_buttons_control: true
                    show_position_control: true
              exclude:
                - state: unavailable
            sort:
              method: none
              reverse: false
              numeric: false
      - type: custom:auto-entities
        card:
          type: custom:layout-card
          layout_type: custom:grid-layout
        card_param: cards
        filter:
          include:
            - domain: camera
              area: $area$
              options:
                show_state: true
                show_name: true
                camera_view: live
                type: picture-entity
          exclude:
            - state: unavailable
        sort:
          method: none
          reverse: false
          numeric: false
      - type: custom:auto-entities
        card:
          type: custom:layout-card
          layout_type: custom:vertical-layout
          layout:
            width: 180
            max_width: 800
        card_param: cards
        filter:
          include:
            - domain: sensor
              area: $area$
              entity_id: '*temp*'
              options:
                type: custom:mini-graph-card
                hour24: true
                hours_to_show: 24
                line_width: 0.5
                points_per_hour: 3
                smoothing: true
                show:
                  labels: true
                entity: null
                entities:
                  - this.entity_id
            - domain: sensor
              area: $area$
              entity_id: '*hum*'
              options:
                type: custom:mini-graph-card
                hour24: true
                hours_to_show: 24
                line_width: 0.5
                points_per_hour: 3
                show:
                  labels: true
                entity: null
                entities:
                  - this.entity_id
          exclude:
            - state: unavailable
        sort:
          method: none
          reverse: false
          numeric: false
        view_layout:
          position: sidebar
    layout:
      max_cols: 4
      width: 300
`

**Comment by daredoes** [comment]
Marking this as closed, as enough time has passed
