### ISSUE TITLE
config not found

### ISSUE THREAD

**Issue by dotKrad** [daredoes/linked-lovelace-ui#9]
Using the example in the wiki I get an error in the console when clicking the "Update All" button in the custom:linked-lovelace-template card
![image](https://user-images.githubusercontent.com/16595330/209903391-ed004265-aff5-4195-88dd-0381d0489774.png)

**Comment by daredoes** [comment]
@dotKrad I have some guesses on what is happening here. Do you use any dashboards managed by Home Assistant? Do you have any dashboards that are entirely YAML? 

Try using the deprecated card with the debug option enabled, it should give more accurate logs as to which part causes the crash. Regardless, I should be able to make it so this isn't a crash, but a warning

**Comment by toti787** [comment]
I am having the same problem as @dotKrad I have 1 dashboard that is managed by Home Assistant rest are manually created via the UI. I don't get any errors in the console when using the Deprecated card but when i refresh the page all views change to BUG - Reload Page
![image](https://user-images.githubusercontent.com/6441632/216477862-82d07bda-3d64-4d7c-bd64-3813ab85db34.png)

if i change the HA managed dashboard to manual then the new card doesn't give an error, but the views don't update. old card still marks everything as BUG - Reload Page when i try to update. no errors in console
HA info.
Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230201.0 - latest

**Comment by daredoes** [comment]
Don't worry about the "Bug - Reload Page", that was me trying to be fancy pulling data. If you minimize and maximize the card using the arrow in the upper right, it should make the bug "go away". @toti787 

I did find a bug involving a recursive error when a template contains a template, which will be patched in 1.3.3. I don't believe this solves the root issue though

**Comment by daredoes** [comment]
@dotKrad the latest update should isolate the update function so that the bad config fails independently, and logs some details about which and hopefully why. If it does, I'd appreciate a text dump, or a photo, of that.

**Comment by toti787** [comment]
Sorry for the late reply but yes, it's fixed on my end with V1.5.0
